"""
General-purpose .docx document builder using python-docx.

Usage as a library:
    from create_docx import DocBuilder

    doc = DocBuilder(title="Report Title")
    doc.add_heading("Section 1", level=1)
    doc.add_paragraph("Some body text.")
    doc.add_bullet_list(["Point A", "Point B", "Point C"])
    doc.add_table(
        headers=["Name", "Score"],
        rows=[["Alice", "90"], ["Bob", "85"]],
    )
    doc.save("output/report.docx")

Usage from the command line (creates a demo document):
    python create_docx.py output/demo.docx
"""

import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH


class DocBuilder:
    def __init__(self, title: str | None = None):
        self.document = Document()
        if title:
            heading = self.document.add_heading(title, level=0)
            heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    def add_heading(self, text: str, level: int = 1):
        self.document.add_heading(text, level=level)
        return self

    def add_paragraph(self, text: str):
        self.document.add_paragraph(text)
        return self

    def add_bullet_list(self, items: list[str]):
        for item in items:
            self.document.add_paragraph(item, style="List Bullet")
        return self

    def add_numbered_list(self, items: list[str]):
        for item in items:
            self.document.add_paragraph(item, style="List Number")
        return self

    def add_table(self, headers: list[str], rows: list[list[str]]):
        table = self.document.add_table(rows=1, cols=len(headers))
        table.style = "Light Grid Accent 1"
        header_cells = table.rows[0].cells
        for i, header in enumerate(headers):
            header_cells[i].text = header
        for row in rows:
            cells = table.add_row().cells
            for i, value in enumerate(row):
                cells[i].text = str(value)
        return self

    def add_page_break(self):
        self.document.add_page_break()
        return self

    def save(self, path: str):
        out_path = Path(path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        self.document.save(out_path)
        return out_path


def _demo(path: str):
    doc = DocBuilder(title="Sample Document")
    doc.add_heading("Introduction", level=1)
    doc.add_paragraph("This document was generated by create_docx.py.")
    doc.add_heading("Key Points", level=1)
    doc.add_bullet_list(["First point", "Second point", "Third point"])
    doc.add_heading("Data", level=1)
    doc.add_table(
        headers=["Item", "Value"],
        rows=[["Alpha", "1"], ["Beta", "2"], ["Gamma", "3"]],
    )
    saved_path = doc.save(path)
    print(f"Saved: {saved_path}")


if __name__ == "__main__":
    output_path = sys.argv[1] if len(sys.argv) > 1 else "output/demo.docx"
    _demo(output_path)
